export type EventTier = "major" | "moderate" | "minor";

export interface SaleEvent {
  id: string;
  name: string;
  month: number; // 0-11
  date: string;
  tier: EventTier;
  whatToBuy: string;
  discount: string;
  flipNote: string;
}

export const saleEvents: SaleEvent[] = [
  // ── January ──
  {
    id: "jan-new-year",
    name: "New Year Sales",
    month: 0,
    date: "Jan 1-7",
    tier: "moderate",
    whatToBuy: "Post-holiday clearance — winter clothing, heaters, leftover holiday stock.",
    discount: "Up to 70% off",
    flipNote: "Buy clearance winter gear in early January, hold and flip next fall for 30-50% profit.",
  },
  {
    id: "jan-mlk",
    name: "MLK Day Sales",
    month: 0,
    date: "Jan 15",
    tier: "minor",
    whatToBuy: "Mattresses, furniture.",
    discount: "30-50% off",
    flipNote: "Mattress deals are decent but Labor Day/Memorial Day are better — wait if you can.",
  },
  {
    id: "jan-winter-clearance",
    name: "Winter Clearance",
    month: 0,
    date: "All month",
    tier: "moderate",
    whatToBuy: "Winter clothing, heaters, snow gear.",
    discount: "50-80% off",
    flipNote: "Deep clearance on winter apparel — buy and hold for next season to flip at full price.",
  },

  // ── February ──
  {
    id: "feb-presidents",
    name: "Presidents Day Sales",
    month: 1,
    date: "Feb 19",
    tier: "moderate",
    whatToBuy: "Mattresses, appliances, furniture.",
    discount: "40-60% off",
    flipNote: "One of the best mattress sales of the year — buy now, flip older units locally.",
  },
  {
    id: "feb-super-bowl-tv",
    name: "Super Bowl TV Sales",
    month: 1,
    date: "Early Feb",
    tier: "moderate",
    whatToBuy: "TVs, soundbars, home theater gear.",
    discount: "30-50% off",
    flipNote: "Buy last-year's TV models and flip on eBay/Marketplace for 15-25% margin.",
  },
  {
    id: "feb-valentines",
    name: "Valentine's Day",
    month: 1,
    date: "Feb 14",
    tier: "minor",
    whatToBuy: "Jewelry, chocolate, flowers.",
    discount: "20-40% off (post-Feb 14)",
    flipNote: "Buy discounted jewelry after Feb 14, hold for next holiday season to resell.",
  },

  // ── March ──
  {
    id: "mar-spring",
    name: "Spring Sales",
    month: 2,
    date: "Mid-March",
    tier: "minor",
    whatToBuy: "Clothing, home goods.",
    discount: "20-40% off",
    flipNote: "Moderate deals — better to wait for Memorial Day for big-ticket items.",
  },
  {
    id: "mar-st-patricks",
    name: "St. Patrick's Day",
    month: 2,
    date: "Mar 17",
    tier: "minor",
    whatToBuy: "Niche products, themed apparel.",
    discount: "20-30% off",
    flipNote: "Limited flip potential — mostly novelty items.",
  },

  // ── April ──
  {
    id: "apr-amazon-spring",
    name: "Amazon Spring Sale",
    month: 3,
    date: "April",
    tier: "major",
    whatToBuy: "Electronics, home goods, Amazon devices.",
    discount: "30-60% off",
    flipNote: "Buy electronics on Amazon Spring Sale, flip on eBay for 20-30% profit.",
  },
  {
    id: "apr-tax-refund",
    name: "Tax Refund Sales",
    month: 3,
    date: "All month",
    tier: "moderate",
    whatToBuy: "Big-ticket items — furniture, appliances, electronics.",
    discount: "20-40% off",
    flipNote: "Retailers target refund recipients — negotiate for stackable discounts.",
  },
  {
    id: "apr-easter",
    name: "Easter Sales",
    month: 3,
    date: "Varies",
    tier: "minor",
    whatToBuy: "Candy, spring clothing.",
    discount: "30-50% off (post-Easter)",
    flipNote: "Post-Easter candy clearance is great for bulk reselling at events.",
  },

  // ── May ──
  {
    id: "may-mothers-day",
    name: "Mother's Day",
    month: 4,
    date: "May 12",
    tier: "moderate",
    whatToBuy: "Jewelry, electronics, flowers.",
    discount: "20-40% off",
    flipNote: "Buy electronics gifts on sale, flip unopened units after the holiday.",
  },
  {
    id: "may-memorial",
    name: "Memorial Day Sales",
    month: 4,
    date: "May 27",
    tier: "major",
    whatToBuy: "Mattresses, appliances, outdoor furniture.",
    discount: "50-70% off",
    flipNote: "Best mattress deals of the year alongside Labor Day — buy and flip old mattress locally.",
  },
  {
    id: "may-spring-clearance",
    name: "Spring Clearance",
    month: 4,
    date: "Late May",
    tier: "moderate",
    whatToBuy: "Spring clothing, garden items.",
    discount: "50-70% off",
    flipNote: "Clearance spring apparel — buy and hold for next year to resell.",
  },

  // ── June ──
  {
    id: "jun-prime-announce",
    name: "Amazon Prime Day (announced)",
    month: 5,
    date: "Mid-July (announced June)",
    tier: "major",
    whatToBuy: "Prime Day previews, early deals.",
    discount: "Up to 50% off previews",
    flipNote: "Watch for early Prime Day leaks to plan your flip inventory ahead of time.",
  },
  {
    id: "jun-fathers-day",
    name: "Father's Day",
    month: 5,
    date: "Jun 16",
    tier: "moderate",
    whatToBuy: "Tools, electronics, sporting goods.",
    discount: "20-40% off",
    flipNote: "Tool deals are strong — buy name-brand tools and flip on Marketplace for 15-25% profit.",
  },
  {
    id: "jun-summer",
    name: "Summer Sales",
    month: 5,
    date: "All month",
    tier: "moderate",
    whatToBuy: "Outdoor gear, grills, patio furniture.",
    discount: "20-40% off",
    flipNote: "Grills and outdoor items — better deals come in August clearance.",
  },

  // ── July ──
  {
    id: "jul-prime-day",
    name: "Amazon Prime Day",
    month: 6,
    date: "Mid-July",
    tier: "major",
    whatToBuy: "Electronics, Amazon devices, home goods — biggest Amazon event.",
    discount: "40-70% off",
    flipNote: "Buy electronics on Prime Day, flip on eBay for 20-30% profit. Best flip event of summer.",
  },
  {
    id: "jul-4th",
    name: "4th of July Sales",
    month: 6,
    date: "Jul 4",
    tier: "moderate",
    whatToBuy: "Everything, especially outdoor and seasonal.",
    discount: "30-50% off",
    flipNote: "Outdoor furniture deals — buy and hold for next spring to flip at full price.",
  },
  {
    id: "jul-bf-july",
    name: "Black Friday in July",
    month: 6,
    date: "Various (mid-July)",
    tier: "moderate",
    whatToBuy: "Target, Best Buy competing with Prime Day — electronics, appliances.",
    discount: "30-50% off",
    flipNote: "Compare with Prime Day — sometimes retailers beat Amazon on specific items.",
  },

  // ── August ──
  {
    id: "aug-back-to-school",
    name: "Back to School",
    month: 7,
    date: "All month",
    tier: "major",
    whatToBuy: "Laptops, supplies, clothing.",
    discount: "20-40% off",
    flipNote: "Buy laptops on Back to School deals, flip after semester starts when demand stays high.",
  },
  {
    id: "aug-tax-free",
    name: "Tax-Free Weekends",
    month: 7,
    date: "Varies by state",
    tier: "moderate",
    whatToBuy: "No sales tax on clothing, electronics, school supplies (state-dependent).",
    discount: "Save 5-10% tax",
    flipNote: "Stack tax-free with sale prices for maximum margin on resale electronics.",
  },
  {
    id: "aug-summer-clearance",
    name: "Summer Clearance",
    month: 7,
    date: "Late Aug",
    tier: "moderate",
    whatToBuy: "Summer items, outdoor gear, grills.",
    discount: "50-70% off",
    flipNote: "Best time to buy outdoor/patio — hold and flip next spring for 40-60% profit.",
  },

  // ── September ──
  {
    id: "sep-labor-day",
    name: "Labor Day Sales",
    month: 8,
    date: "Sep 2",
    tier: "major",
    whatToBuy: "Mattresses, appliances, furniture.",
    discount: "50-70% off",
    flipNote: "Best mattress deals of the year alongside Memorial Day — flip opportunities on used units.",
  },
  {
    id: "sep-fall",
    name: "Fall Sales",
    month: 8,
    date: "All month",
    tier: "minor",
    whatToBuy: "Transition clothing.",
    discount: "20-40% off",
    flipNote: "Moderate deals — wait for Black Friday for bigger discounts.",
  },
  {
    id: "sep-iphone-launch",
    name: "iPhone Launch",
    month: 8,
    date: "Mid-Sep",
    tier: "moderate",
    whatToBuy: "Previous iPhone models drop in price.",
    discount: "15-25% off",
    flipNote: "Buy discounted previous-gen iPhones, flip on Swappa/Gazelle for steady margin.",
  },

  // ── October ──
  {
    id: "oct-fall-prime",
    name: "Amazon Fall Prime Sale",
    month: 9,
    date: "Oct",
    tier: "major",
    whatToBuy: "Second Prime event of the year — electronics, home, Amazon devices.",
    discount: "30-60% off",
    flipNote: "Second-best Amazon flip window after July Prime Day — stock up for holiday resale.",
  },
  {
    id: "oct-halloween",
    name: "Halloween Sales",
    month: 9,
    date: "Oct 31",
    tier: "minor",
    whatToBuy: "Costumes, candy.",
    discount: "30-50% off (post-Halloween)",
    flipNote: "Post-Halloween costume clearance — buy and flip next October for 50%+ profit.",
  },
  {
    id: "oct-pre-bf-teasers",
    name: "Pre-Black Friday Teasers",
    month: 9,
    date: "Late Oct",
    tier: "moderate",
    whatToBuy: "Early deals at major retailers.",
    discount: "20-40% off",
    flipNote: "Preview deals — use to price-match later. Real discounts hit in November.",
  },

  // ── November ──
  {
    id: "nov-pre-bf",
    name: "Pre-Black Friday Sales",
    month: 10,
    date: "Early Nov",
    tier: "moderate",
    whatToBuy: "Early access deals across categories.",
    discount: "20-40% off",
    flipNote: "Good for planning — but wait for Black Friday proper for the deepest cuts.",
  },
  {
    id: "nov-black-friday",
    name: "Black Friday",
    month: 10,
    date: "Nov 29",
    tier: "major",
    whatToBuy: "Everything — biggest retail event of the year. TVs, laptops, appliances, toys.",
    discount: "40-70% off",
    flipNote: "Buy TVs and electronics on Black Friday, flip on eBay/Marketplace for 20-40% profit.",
  },
  {
    id: "nov-small-business",
    name: "Small Business Saturday",
    month: 10,
    date: "Nov 30",
    tier: "minor",
    whatToBuy: "Small retailers, local shops.",
    discount: "10-30% off",
    flipNote: "Limited flip potential — focus on unique/niche items with resale value.",
  },
  {
    id: "nov-cyber-monday",
    name: "Cyber Monday",
    month: 10,
    date: "Dec 2",
    tier: "major",
    whatToBuy: "Online-only deals, electronics, software subscriptions.",
    discount: "40-60% off",
    flipNote: "Best online electronics deals — buy and flip same week while prices are still high elsewhere.",
  },

  // ── December ──
  {
    id: "dec-cyber-week",
    name: "Cyber Week",
    month: 11,
    date: "Dec 2-6",
    tier: "major",
    whatToBuy: "Extended Cyber Monday deals — electronics, home, apparel.",
    discount: "30-60% off",
    flipNote: "Extended flip window from Cyber Monday — stock inventory for holiday resale.",
  },
  {
    id: "dec-green-monday",
    name: "Green Monday",
    month: 11,
    date: "Dec 9",
    tier: "moderate",
    whatToBuy: "Last chance for shipping — retailers push final deals.",
    discount: "20-40% off",
    flipNote: "Final online deals before shipping cutoffs — good for quick flips before Christmas.",
  },
  {
    id: "dec-last-minute",
    name: "Last-minute deals",
    month: 11,
    date: "Dec 20-24",
    tier: "minor",
    whatToBuy: "Rush shipping deals, gift items.",
    discount: "10-30% off",
    flipNote: "Limited flip potential — focus on in-demand gift items.",
  },
  {
    id: "dec-after-christmas",
    name: "After-Christmas Clearance",
    month: 11,
    date: "Dec 26-31",
    tier: "major",
    whatToBuy: "Best clearance of the year — toys, decorations, electronics, winter apparel.",
    discount: "50-80% off",
    flipNote: "Buy toys and decorations at 70%+ off, hold and flip next holiday season for huge margins.",
  },
];

export const buyByCategory = [
  { category: "TVs", month: "November (Black Friday)", discount: "40-60%", why: "Retailers clear inventory" },
  { category: "Laptops", month: "August / November", discount: "20-40%", why: "Back to School + holiday sales" },
  { category: "Mattresses", month: "May & September", discount: "50-70%", why: "Memorial Day & Labor Day" },
  { category: "Clothing", month: "January & July", discount: "60-80%", why: "End-of-season clearance" },
  { category: "Toys", month: "December (after Christmas)", discount: "50-75%", why: "Clearance" },
  { category: "iPhones", month: "September", discount: "15-25%", why: "New model launch" },
  { category: "Appliances", month: "September & November", discount: "30-50%", why: "Labor Day & Black Friday" },
  { category: "Outdoor / Patio", month: "August & September", discount: "50-70%", why: "End of summer" },
];

export const sellByCategory = [
  { category: "Electronics", month: "December", why: "Holiday gift demand" },
  { category: "Toys", month: "November-December", why: "Christmas shopping" },
  { category: "Winter clothing", month: "October-November", why: "Before winter" },
  { category: "Summer items", month: "April-May", why: "Before summer" },
  { category: "iPhones", month: "October", why: "People waiting for new model settle for used" },
];
